### ISSUE TITLE
KeyError: 'bromwell'

### ISSUE THREAD

**Issue by Ritian-Li** [lukysummer/Movie-Review-Sentiment-Analysis-using-LSTM-in-Pytorch#6]
https://github.com/lukysummer/Movie-Review-Sentiment-Analysis-LSTM-Pytorch/blob/2edcc1e617da9abce0c6c1d5ab1f4d3f47352234/sentiment_analysis_LSTM.py#L38

at line 39
it should be
 `encoded_reviews = [[vocab_to_int.get(word) for word in review.split()] for review in all_reviews]`

**Comment by lukysummer** [comment]
Thank you for the fix!
